package schemachange_test

import (
	"context"
	"math"
	"testing"

	"github.com/jackc/pgx/v5"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/block/pg-sprite/pkg/schemachange"
)

// sequenceBounds reads a sequence's type and declared bounds.
func (f shadowFixture) sequenceBounds(t *testing.T, sequence string) (typ string, minValue, maxValue int64) {
	t.Helper()
	require.NoError(t, f.pool.QueryRow(t.Context(), `
		SELECT seqtypid::regtype::text, seqmin, seqmax
		FROM pg_sequence WHERE seqrelid = to_regclass($1)`,
		pgx.Identifier{f.schema, sequence}.Sanitize()).Scan(&typ, &minValue, &maxValue))
	return typ, minValue, maxValue
}

// Widening an identity column widens its sequence, as the server's own
// ALTER COLUMN … TYPE does: a bound the source sequence took from its old
// type's limit follows the new type, so the live identity is not capped at
// the old type's maximum — the failure the widening was run to prevent. A
// bound the user declared stays as written. The SwappedTable reports the
// identity as the live table now declares it (D5).
func TestCutoverWidensTheIdentitySequenceWithItsColumn(t *testing.T) {
	f := newShadowFixture(t)
	f.exec(t, `
		CREATE TABLE %s.tickets (
			id    bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			seqno integer GENERATED BY DEFAULT AS IDENTITY,
			batch integer GENERATED BY DEFAULT AS IDENTITY (MINVALUE 100 MAXVALUE 100000),
			qty   integer NOT NULL
		)`)
	f.exec(t, `INSERT INTO %s.tickets (qty) SELECT g FROM generate_series(1, 100) g`)
	s := f.stage(t, "tickets", `ALTER TABLE %s.tickets ALTER COLUMN seqno TYPE bigint, ALTER COLUMN batch TYPE bigint`)

	swapped, err := f.cutover(t, s, schemachange.CutoverOptions{})
	require.NoError(t, err)

	typ, minValue, maxValue := f.sequenceBounds(t, "tickets_seqno_seq")
	assert.Equal(t, "bigint", typ)
	assert.Equal(t, int64(1), minValue, "an ascending sequence's minimum of 1 is not a type limit and stays")
	assert.Equal(t, int64(math.MaxInt64), maxValue, "the integer maximum followed the column to bigint")
	typ, minValue, maxValue = f.sequenceBounds(t, "tickets_batch_seq")
	assert.Equal(t, "bigint", typ)
	assert.Equal(t, int64(100), minValue, "a declared bound stays")
	assert.Equal(t, int64(100000), maxValue, "a declared bound stays")

	var seqno schemachange.IdentityColumn
	for _, id := range swapped.IdentityColumns() {
		if id.Column == "seqno" {
			seqno = id
		}
	}
	assert.Equal(t, int64(math.MaxInt64), seqno.Options.Max, "the proof reports the widened bound, not the source's")
	assert.NotEqual(t, s.built.IdentityColumns(), swapped.IdentityColumns(), "the source's options are history once the column is widened")

	var next int64
	require.NoError(t, f.pool.QueryRow(t.Context(), `INSERT INTO `+pgx.Identifier{f.schema, "tickets"}.Sanitize()+` (qty) VALUES (1) RETURNING seqno`).Scan(&next))
	assert.Equal(t, int64(101), next, "the counter continues from where the source left it")
}

// A role granted the source identity sequence keeps that grant on the
// sequence that replaces it, so INSERT … ; SELECT currval(…) works for it
// after the swap as it did before. ADD … AS IDENTITY gives the new
// sequence only the owner's default privileges; the handoff carries the
// source sequence's ACL over and re-reads it (D5, ST-5).
func TestCutoverCarriesTheIdentitySequenceGrants(t *testing.T) {
	f, role := newShadowFixtureWithRole(t)
	f.exec(t, `
		CREATE TABLE %s.tickets (
			id  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			qty integer NOT NULL
		)`)
	f.exec(t, `INSERT INTO %s.tickets (qty) SELECT g FROM generate_series(1, 100) g`)
	f.exec(t, `GRANT USAGE ON SCHEMA %s TO `+pgx.Identifier{role}.Sanitize())
	f.exec(t, `GRANT SELECT, INSERT ON %s.tickets TO `+pgx.Identifier{role}.Sanitize())
	f.exec(t, `GRANT USAGE, SELECT ON SEQUENCE %s.tickets_id_seq TO `+pgx.Identifier{role}.Sanitize())
	insertThenCurrval := func() error {
		tx, err := f.pool.Begin(t.Context())
		require.NoError(t, err)
		defer func() { _ = tx.Rollback(context.WithoutCancel(t.Context())) }()
		_, err = tx.Exec(t.Context(), `SET LOCAL ROLE `+pgx.Identifier{role}.Sanitize())
		require.NoError(t, err)
		_, err = tx.Exec(t.Context(), `INSERT INTO `+pgx.Identifier{f.schema, "tickets"}.Sanitize()+` (qty) VALUES (1)`)
		require.NoError(t, err)
		var id int64
		return tx.QueryRow(t.Context(), `SELECT currval($1::regclass)`, pgx.Identifier{f.schema, "tickets_id_seq"}.Sanitize()).Scan(&id)
	}
	require.NoError(t, insertThenCurrval(), "before the swap")
	s := f.stage(t, "tickets", `ALTER TABLE %s.tickets ALTER COLUMN qty TYPE bigint`)

	_, err := f.cutover(t, s, schemachange.CutoverOptions{})
	require.NoError(t, err)

	assert.NoError(t, insertThenCurrval(), "after the swap")
	var acl string
	require.NoError(t, f.pool.QueryRow(t.Context(), `
		SELECT array_to_string(ARRAY(
			SELECT privilege_type FROM pg_class c, aclexplode(c.relacl) a
			WHERE c.oid = to_regclass($1) AND a.grantee = $2::regrole
			ORDER BY 1), ',')`,
		pgx.Identifier{f.schema, "tickets_id_seq"}.Sanitize(), pgx.Identifier{role}.Sanitize()).Scan(&acl))
	assert.Equal(t, "SELECT,USAGE", acl, "exactly the source sequence's grants, nothing the default ACL added")
}

// An identity sequence the user renamed keeps that name across the swap:
// the server names the recreated sequence after the column, and the
// handoff renames it to the name the source's held (D5).
func TestCutoverKeepsARenamedIdentitySequenceName(t *testing.T) {
	f := newShadowFixture(t)
	f.exec(t, `
		CREATE TABLE %s.tickets (
			id  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			qty integer NOT NULL
		)`)
	f.exec(t, `ALTER SEQUENCE %s.tickets_id_seq RENAME TO ticket_numbers`)
	f.exec(t, `INSERT INTO %s.tickets (qty) SELECT g FROM generate_series(1, 100) g`)
	s := f.stage(t, "tickets", `ALTER TABLE %s.tickets ALTER COLUMN qty TYPE bigint`)

	_, err := f.cutover(t, s, schemachange.CutoverOptions{})
	require.NoError(t, err)

	assert.True(t, f.relationExists(t, "ticket_numbers"))
	assert.False(t, f.relationExists(t, "tickets_id_seq"), "the server-chosen name did not survive the handoff")
	assert.Equal(t, f.schema+".ticket_numbers", f.serialSequence(t, "tickets", "id"))
}
