package schemachange

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"

	"github.com/block/pg-sprite/pkg/schemadiff"
)

// IdentityColumn records one source identity column and the sequence behind
// it. The shadow carries the column as a plain column with
// DEFAULT nextval(<source sequence>), so source and shadow draw from one
// sequence during copy and apply; cutover uses these facts to recreate the
// identity on the live table with the source sequence's options.
type IdentityColumn struct {
	// Column is the column name.
	Column string `json:"column"`
	// Always reports GENERATED ALWAYS (false is GENERATED BY DEFAULT).
	Always bool `json:"always"`
	// SequenceSchema and SequenceName locate the source identity sequence.
	SequenceSchema string `json:"sequence_schema"`
	// SequenceName is the sequence's unqualified name.
	SequenceName string `json:"sequence_name"`
	// Options are the sequence's declared options.
	Options SequenceOptions `json:"options"`
}

// SequenceOptions are the pg_sequence facts cutover replays into ADD
// GENERATED … AS IDENTITY. The counter's current value is deliberately not
// among them: it is a runtime fact that moves with every insert on the
// shared sequence, so cutover reads last_value and is_called from the
// sequence itself at swap time and renders START WITH from that, never from
// the Start recorded here.
type SequenceOptions struct {
	// Start is START WITH.
	Start int64 `json:"start"`
	// Increment is INCREMENT BY.
	Increment int64 `json:"increment"`
	// Min is MINVALUE.
	Min int64 `json:"min"`
	// Max is MAXVALUE.
	Max int64 `json:"max"`
	// Cache is CACHE.
	Cache int64 `json:"cache"`
	// Cycle reports CYCLE.
	Cycle bool `json:"cycle"`
}

// handoffIdentities keeps the source identity columns that still exist on
// the shadow after the schema change, in source order. A change that drops
// an identity column leaves the shadow nothing to hand the sequence to: the
// column is not part of the proof, and the sequence ends with the old table
// at cutover.
func handoffIdentities(identities []IdentityColumn, shadow schemadiff.Model) []IdentityColumn {
	onShadow := make(map[string]bool, len(shadow.Columns))
	for _, c := range shadow.Columns {
		onShadow[c.Name] = true
	}
	kept := make([]IdentityColumn, 0, len(identities))
	for _, id := range identities {
		if onShadow[id.Column] {
			kept = append(kept, id)
		}
	}
	return kept
}

// readIdentityColumns lists the table's identity columns with their
// sequences. Each identity column must own exactly one sequence through an
// internal (deptype 'i') pg_depend edge; an identity column without that
// edge is a catalog the engine does not understand, and the builder fails
// closed rather than guess which sequence to hand over.
func readIdentityColumns(ctx context.Context, tx pgx.Tx, oid uint32) ([]IdentityColumn, error) {
	rows, err := tx.Query(ctx, `
		SELECT a.attname, a.attidentity = 'a',
		       sn.nspname, s.relname,
		       q.seqstart, q.seqincrement, q.seqmin, q.seqmax, q.seqcache, q.seqcycle
		FROM pg_attribute a
		LEFT JOIN pg_depend d
		       ON d.refclassid = 'pg_class'::regclass AND d.refobjid = a.attrelid AND d.refobjsubid = a.attnum
		      AND d.classid = 'pg_class'::regclass AND d.deptype = 'i'
		LEFT JOIN pg_class s ON s.oid = d.objid AND s.relkind = 'S'
		LEFT JOIN pg_namespace sn ON sn.oid = s.relnamespace
		LEFT JOIN pg_sequence q ON q.seqrelid = s.oid
		WHERE a.attrelid = $1 AND a.attidentity <> '' AND NOT a.attisdropped
		ORDER BY a.attnum`, oid)
	if err != nil {
		return nil, fmt.Errorf("read identity columns: %w", err)
	}
	identities, err := pgx.CollectRows(rows, func(row pgx.CollectableRow) (IdentityColumn, error) {
		var id IdentityColumn
		var sequenceSchema, sequenceName *string
		var start, increment, minValue, maxValue, cache *int64
		var cycle *bool
		if err := row.Scan(&id.Column, &id.Always, &sequenceSchema, &sequenceName, &start, &increment, &minValue, &maxValue, &cache, &cycle); err != nil {
			return IdentityColumn{}, err
		}
		if sequenceSchema == nil || sequenceName == nil || start == nil || increment == nil || minValue == nil || maxValue == nil || cache == nil || cycle == nil {
			// INV: ST-6
			return IdentityColumn{}, refuse(CauseSourceShape, nil, "identity column %s has no internally owned sequence", id.Column)
		}
		id.SequenceSchema, id.SequenceName = *sequenceSchema, *sequenceName
		id.Options = SequenceOptions{Start: *start, Increment: *increment, Min: *minValue, Max: *maxValue, Cache: *cache, Cycle: *cycle}
		return id, nil
	})
	if err != nil {
		return nil, fmt.Errorf("read identity columns: %w", err)
	}
	return identities, nil
}

// applyIdentityDefaults points each shadow identity column at the source's
// sequence. LIKE … EXCLUDING IDENTITY left the column plain, so the default
// is the only thing that makes the shadow and source share the counter.
func applyIdentityDefaults(ctx context.Context, tx pgx.Tx, schema, shadow string, identities []IdentityColumn) error {
	table := pgx.Identifier{schema, shadow}.Sanitize()
	for _, id := range identities {
		sequence := pgx.Identifier{id.SequenceSchema, id.SequenceName}.Sanitize()
		sql, err := formatSQL(ctx, tx, "ALTER TABLE %s ALTER COLUMN %s SET DEFAULT nextval(%L::regclass)",
			table, pgx.Identifier{id.Column}.Sanitize(), sequence)
		if err != nil {
			return err
		}
		if _, err := tx.Exec(ctx, sql); err != nil {
			return fmt.Errorf("point shadow column %s at sequence %s: %w", id.Column, sequence, err)
		}
	}
	return nil
}

// verifyIdentityDefaults proves each handed-off identity column carries
// DEFAULT nextval(<source sequence>) on the shadow: a plain column (no
// identity of its own) whose default is the source's sequence, exactly as
// applyIdentityDefaults left it. The build runs it after the gated
// statement, so a statement that replaced the column under the same name
// is refused rather than recorded as a handoff; the inspection runs it so
// a shadow whose default was stripped or re-pointed is refused. The
// comparison is on the sequence's OID, so a renamed sequence still matches
// and a re-created one does not.
func verifyIdentityDefaults(ctx context.Context, tx pgx.Tx, shadowOID uint32, identities []IdentityColumn) error {
	for _, id := range identities {
		var identity string
		var defaultsToSequence bool
		err := tx.QueryRow(ctx, `
			SELECT a.attidentity::text,
			       EXISTS (
			           SELECT 1
			           FROM pg_depend s
			           WHERE s.classid = 'pg_attrdef'::regclass AND s.objid = d.oid
			             AND s.refclassid = 'pg_class'::regclass AND s.refobjid = to_regclass($3))
			FROM pg_attribute a
			LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
			WHERE a.attrelid = $1 AND a.attname = $2 AND NOT a.attisdropped`, shadowOID, id.Column,
			pgx.Identifier{id.SequenceSchema, id.SequenceName}.Sanitize()).Scan(&identity, &defaultsToSequence)
		if errors.Is(err, pgx.ErrNoRows) {
			// INV: ST-5
			return refuse(CauseIdentityHandoff, nil, "shadow has no column %s to carry the identity handoff", id.Column)
		}
		if err != nil {
			return fmt.Errorf("read shadow default for %s: %w", id.Column, err)
		}
		if identity != "" {
			// INV: ST-5
			return refuse(CauseIdentityHandoff, nil, "shadow column %s is an identity column of its own, not a handoff from the source sequence", id.Column)
		}
		if !defaultsToSequence {
			// INV: ST-5
			return refuse(CauseIdentityHandoff, nil, "shadow column %s does not default to the source sequence %s.%s", id.Column, id.SequenceSchema, id.SequenceName)
		}
	}
	return nil
}
