package schemachange

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5"
)

// IdentityColumn records one source identity column and the sequence behind
// it. The shadow carries the column as a plain column with
// DEFAULT nextval(<source sequence>), so source and shadow draw from one
// sequence during copy and apply; cutover uses these facts to recreate the
// identity on the live table with the source sequence's options.
type IdentityColumn struct {
	// Column is the column name.
	Column string
	// Always reports GENERATED ALWAYS (false is GENERATED BY DEFAULT).
	Always bool
	// SequenceSchema and SequenceName locate the source identity sequence.
	SequenceSchema string
	// SequenceName is the sequence's unqualified name.
	SequenceName string
	// Options are the sequence's declared options.
	Options SequenceOptions
}

// SequenceOptions are the pg_sequence facts cutover replays into ADD
// GENERATED … AS IDENTITY.
type SequenceOptions struct {
	// Start is START WITH.
	Start int64
	// Increment is INCREMENT BY.
	Increment int64
	// Min is MINVALUE.
	Min int64
	// Max is MAXVALUE.
	Max int64
	// Cache is CACHE.
	Cache int64
	// Cycle reports CYCLE.
	Cycle bool
}

// readIdentityColumns lists the table's identity columns with their
// sequences. Each identity column must own exactly one sequence through an
// internal (deptype 'i') pg_depend edge; an identity column without that
// edge is a catalog the engine does not understand, and the builder fails
// closed rather than guess which sequence to hand over.
func readIdentityColumns(ctx context.Context, tx pgx.Tx, oid uint32) ([]IdentityColumn, error) {
	rows, err := tx.Query(ctx, `
		SELECT a.attname, a.attidentity = 'a',
		       sn.nspname, s.relname,
		       q.seqstart, q.seqincrement, q.seqmin, q.seqmax, q.seqcache, q.seqcycle
		FROM pg_attribute a
		LEFT JOIN pg_depend d
		       ON d.refclassid = 'pg_class'::regclass AND d.refobjid = a.attrelid AND d.refobjsubid = a.attnum
		      AND d.classid = 'pg_class'::regclass AND d.deptype = 'i'
		LEFT JOIN pg_class s ON s.oid = d.objid AND s.relkind = 'S'
		LEFT JOIN pg_namespace sn ON sn.oid = s.relnamespace
		LEFT JOIN pg_sequence q ON q.seqrelid = s.oid
		WHERE a.attrelid = $1 AND a.attidentity <> '' AND NOT a.attisdropped
		ORDER BY a.attnum`, oid)
	if err != nil {
		return nil, fmt.Errorf("read identity columns: %w", err)
	}
	identities, err := pgx.CollectRows(rows, func(row pgx.CollectableRow) (IdentityColumn, error) {
		var id IdentityColumn
		var sequenceSchema, sequenceName *string
		var start, increment, minValue, maxValue, cache *int64
		var cycle *bool
		if err := row.Scan(&id.Column, &id.Always, &sequenceSchema, &sequenceName, &start, &increment, &minValue, &maxValue, &cache, &cycle); err != nil {
			return IdentityColumn{}, err
		}
		if sequenceSchema == nil || sequenceName == nil || start == nil || increment == nil || minValue == nil || maxValue == nil || cache == nil || cycle == nil {
			// INV: ST-6
			return IdentityColumn{}, fmt.Errorf("%w: identity column %s has no internally owned sequence", ErrInvariantViolation, id.Column)
		}
		id.SequenceSchema, id.SequenceName = *sequenceSchema, *sequenceName
		id.Options = SequenceOptions{Start: *start, Increment: *increment, Min: *minValue, Max: *maxValue, Cache: *cache, Cycle: *cycle}
		return id, nil
	})
	if err != nil {
		return nil, fmt.Errorf("read identity columns: %w", err)
	}
	return identities, nil
}

// applyIdentityDefaults points each shadow identity column at the source's
// sequence. LIKE … EXCLUDING IDENTITY left the column plain, so the default
// is the only thing that makes the shadow and source share the counter.
func applyIdentityDefaults(ctx context.Context, tx pgx.Tx, schema, shadow string, identities []IdentityColumn) error {
	table := pgx.Identifier{schema, shadow}.Sanitize()
	for _, id := range identities {
		sequence := pgx.Identifier{id.SequenceSchema, id.SequenceName}.Sanitize()
		sql, err := formatSQL(ctx, tx, "ALTER TABLE %s ALTER COLUMN %s SET DEFAULT nextval(%L::regclass)",
			table, pgx.Identifier{id.Column}.Sanitize(), sequence)
		if err != nil {
			return err
		}
		if _, err := tx.Exec(ctx, sql); err != nil {
			return fmt.Errorf("point shadow column %s at sequence %s: %w", id.Column, sequence, err)
		}
	}
	return nil
}
