package schemachange_test

import (
	"fmt"
	"testing"

	"github.com/jackc/pgx/v5"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/block/pg-sprite/pkg/preflight"
	"github.com/block/pg-sprite/pkg/schemachange"
)

// Inspecting a shadow re-derives the whole build proof from the catalog:
// OIDs, fingerprints, copy columns, identity handoffs and fidelity all
// match what the build returned, so a resume can compare them with its
// checkpoint instead of trusting a shadow blindly.
func TestInspectShadowRederivesTheBuiltProof(t *testing.T) {
	f := newShadowFixture(t)
	f.exec(t, `
		CREATE TABLE %s.orders (
			id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			qty integer NOT NULL,
			note text,
			price integer NOT NULL,
			doubled integer GENERATED ALWAYS AS (price * 2) STORED
		) WITH (fillfactor = 70)`)
	f.exec(t, `COMMENT ON TABLE %s.orders IS 'customer orders'`)
	f.exec(t, `CREATE INDEX orders_note_idx ON %s.orders (note)`)
	lock := f.lock(t, "orders")
	target := f.prove(t, "orders")
	built, err := schemachange.BuildShadow(t.Context(), f.pool, lock, target, f.alter(t, `ALTER TABLE %s.orders ALTER COLUMN qty TYPE bigint`), schemachange.Options{})
	require.NoError(t, err)

	inspected, err := schemachange.InspectShadow(t.Context(), f.pool, lock, target, schemachange.Options{})
	require.NoError(t, err)

	assert.Equal(t, built, inspected)
	assert.NotEqual(t, inspected.SourceFingerprint(), inspected.TargetFingerprint(), "the inspected proof still shows the change")
}

// A change that drops one of the source's identity columns leaves the
// shadow with nothing to hand that sequence to. The proof carries only the
// identity column the shadow kept, and inspection re-derives the same
// proof: a correctly built shadow is not mistaken for one whose handoff was
// stripped.
func TestInspectShadowAcceptsAShadowWhoseIdentityColumnTheChangeDropped(t *testing.T) {
	f := newShadowFixture(t)
	f.exec(t, `
		CREATE TABLE %s.widgets (
			id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			seqno bigint GENERATED BY DEFAULT AS IDENTITY,
			qty integer NOT NULL
		)`)
	lock := f.lock(t, "widgets")
	target := f.prove(t, "widgets")
	built, err := schemachange.BuildShadow(t.Context(), f.pool, lock, target, f.alter(t, `ALTER TABLE %s.widgets DROP COLUMN seqno`), schemachange.Options{})
	require.NoError(t, err)
	require.Len(t, built.IdentityColumns(), 1, "only the kept identity column is handed over")
	assert.Equal(t, "id", built.IdentityColumns()[0].Column)
	assert.Equal(t, []string{"id", "qty"}, built.CopyColumns())

	inspected, err := schemachange.InspectShadow(t.Context(), f.pool, lock, target, schemachange.Options{})
	require.NoError(t, err)

	assert.Equal(t, built, inspected)
}

// A resume that finds no shadow is told so distinctly, so the caller can
// fall back to a fresh build rather than treat it as a failure.
func TestInspectShadowReportsAMissingShadow(t *testing.T) {
	f := newShadowFixture(t)
	f.exec(t, `
		CREATE TABLE %s.widgets (
			id bigint PRIMARY KEY
		)`)
	_, err := schemachange.InspectShadow(t.Context(), f.pool, f.lock(t, "widgets"), f.prove(t, "widgets"), schemachange.Options{})
	assert.ErrorIs(t, err, schemachange.ErrShadowNotFound)
}

// A shadow whose identity handoff was stripped would insert nulls into its
// key once rows are copied. Inspection refuses it: the default on the shadow
// must still be the source's sequence.
func TestInspectShadowRefusesAShadowWhoseIdentityDefaultWasStripped(t *testing.T) {
	f := newShadowFixture(t)
	f.exec(t, `
		CREATE TABLE %s.orders (
			id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			qty integer NOT NULL
		)`)
	lock := f.lock(t, "orders")
	target := f.prove(t, "orders")
	_, err := schemachange.BuildShadow(t.Context(), f.pool, lock, target, f.alter(t, `ALTER TABLE %s.orders ALTER COLUMN qty TYPE bigint`), schemachange.Options{})
	require.NoError(t, err)
	shadow := schemachange.ShadowName(f.schema, "orders")
	f.exec(t, fmt.Sprintf(`ALTER TABLE %%s.%s ALTER COLUMN id DROP DEFAULT`, pgx.Identifier{shadow}.Sanitize()))

	_, err = schemachange.InspectShadow(t.Context(), f.pool, lock, target, schemachange.Options{})
	assert.ErrorIs(t, err, schemachange.ErrInvariantViolation)
	assert.Equal(t, schemachange.CauseIdentityHandoff, schemachange.RefusalCauseOf(err))
}

// A shadow whose identity default was re-pointed at a sequence of its own
// would split the key space from the source. The check compares sequence
// identity, not merely that some default exists.
func TestInspectShadowRefusesAShadowDefaultingToAnotherSequence(t *testing.T) {
	f := newShadowFixture(t)
	f.exec(t, `
		CREATE TABLE %s.orders (
			id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			qty integer NOT NULL
		)`)
	lock := f.lock(t, "orders")
	target := f.prove(t, "orders")
	_, err := schemachange.BuildShadow(t.Context(), f.pool, lock, target, f.alter(t, `ALTER TABLE %s.orders ALTER COLUMN qty TYPE bigint`), schemachange.Options{})
	require.NoError(t, err)
	shadow := schemachange.ShadowName(f.schema, "orders")
	f.exec(t, `CREATE SEQUENCE %s.other_seq`)
	f.exec(t, fmt.Sprintf(`ALTER TABLE %%s.%s ALTER COLUMN id SET DEFAULT nextval('%%s.other_seq')`, pgx.Identifier{shadow}.Sanitize()))

	_, err = schemachange.InspectShadow(t.Context(), f.pool, lock, target, schemachange.Options{})
	assert.ErrorIs(t, err, schemachange.ErrInvariantViolation)
	assert.Equal(t, schemachange.CauseIdentityHandoff, schemachange.RefusalCauseOf(err))
}

// A table under the shadow's name owned by someone else is not this
// engine's shadow and is never reported as one.
func TestInspectShadowRefusesAShadowWithAnotherOwner(t *testing.T) {
	f, other := newShadowFixtureWithRole(t)
	f.exec(t, `
		CREATE TABLE %s.widgets (
			id bigint PRIMARY KEY
		)`)
	shadow := schemachange.ShadowName(f.schema, "widgets")
	f.exec(t, fmt.Sprintf(`CREATE TABLE %%s.%s (id bigint)`, pgx.Identifier{shadow}.Sanitize()))
	f.exec(t, fmt.Sprintf(`ALTER TABLE %%s.%s OWNER TO %s`, pgx.Identifier{shadow}.Sanitize(), pgx.Identifier{other}.Sanitize()))

	_, err := schemachange.InspectShadow(t.Context(), f.pool, f.lock(t, "widgets"), f.prove(t, "widgets"), schemachange.Options{})
	assert.ErrorIs(t, err, schemachange.ErrInvariantViolation)
	assert.Equal(t, schemachange.CauseForeignRelation, schemachange.RefusalCauseOf(err))
}

// The source must still have the shape the proof was minted for: a trigger
// added after the build is the same refusal the build itself would raise.
func TestInspectShadowRefusesASourceThatChangedShapeSinceTheProof(t *testing.T) {
	f := newShadowFixture(t)
	f.exec(t, `
		CREATE TABLE %s.widgets (
			id bigint PRIMARY KEY,
			qty integer NOT NULL
		)`)
	lock := f.lock(t, "widgets")
	target := f.prove(t, "widgets")
	_, err := schemachange.BuildShadow(t.Context(), f.pool, lock, target, f.alter(t, `ALTER TABLE %s.widgets ALTER COLUMN qty TYPE bigint`), schemachange.Options{})
	require.NoError(t, err)
	f.exec(t, `
		CREATE FUNCTION %s.noop() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$`)
	f.exec(t, `CREATE TRIGGER widgets_noop BEFORE INSERT ON %s.widgets FOR EACH ROW EXECUTE FUNCTION %s.noop()`)

	_, err = schemachange.InspectShadow(t.Context(), f.pool, lock, target, schemachange.Options{})
	var shape *preflight.UnsupportedCopySwapShapeError
	assert.ErrorAs(t, err, &shape)
}
