package schemadiff

import (
	"errors"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/block/pg-sprite/pkg/statement"
)

// Rendered SQL is the product artifact a pull produces, so its exact text
// is a legitimate unit-test surface (unlike log output).
func TestRenderGolden(t *testing.T) {
	m := base()
	m.Columns = append(m.Columns,
		Column{Name: "created_at", Type: "timestamp with time zone", NotNull: true, Default: "now()"},
		Column{Name: "doubled", Type: "integer", Generated: true, Default: "(id * 2)"},
		Column{Name: "seq", Type: "bigint", NotNull: true, Identity: IdentityByDefault},
		Column{Name: "note", Type: "text"},
	)
	m.Constraints = append(m.Constraints, Constraint{Name: "name_len", Def: "CHECK ((length((name)::text) > 0))"})

	out, err := Render(m)
	require.NoError(t, err)
	assert.Equal(t, `CREATE TABLE "events" (
    "id" bigint NOT NULL,
    "name" character varying(50) NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "doubled" integer GENERATED ALWAYS AS ((id * 2)) STORED,
    "seq" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "note" text,
    CONSTRAINT "events_pkey" PRIMARY KEY (id),
    CONSTRAINT "name_len" CHECK ((length((name)::text) > 0))
);

CREATE INDEX events_name_idx ON events USING btree (name);
`, out)
}

// A serial column renders back to its pseudo-type so the desired file
// recreates the owned sequence on the scratch schema. All three
// integer-family mappings are exercised so a typo in any one map entry
// fails a test rather than shipping a wrong pseudo-type.
func TestRenderSerialColumn(t *testing.T) {
	tests := []struct {
		colType string
		want    string
	}{
		{"smallint", "smallserial"},
		{"integer", "serial"},
		{"bigint", "bigserial"},
	}
	for _, tt := range tests {
		t.Run(tt.colType, func(t *testing.T) {
			m := base()
			m.Columns[0] = Column{
				Name: "id", Type: tt.colType, NotNull: true,
				Default: "nextval('events_id_seq'::regclass)", SequenceDefault: true, SequenceOwned: true,
			}

			out, err := Render(m)
			require.NoError(t, err)
			assert.Contains(t, out, `"id" `+tt.want+` NOT NULL`)
		})
	}
}

// Sequence-backed defaults that are not the canonical serial form fail
// closed: a rendered file could never recreate the sequence they reference.
func TestRenderRefusesUnrenderableSequenceDefaults(t *testing.T) {
	tests := []struct {
		name string
		col  Column
	}{
		{"shared sequence", Column{
			Name: "id", Type: "bigint", NotNull: true,
			Default: "nextval('global_id_seq'::regclass)", SequenceDefault: true,
		}},
		{"standalone sequence with the serial-style name", Column{
			Name: "id", Type: "bigint", NotNull: true,
			Default: "nextval('events_id_seq'::regclass)", SequenceDefault: true, SequenceOwned: false,
		}},
		{"owned sequence with a non-serial name", Column{
			Name: "id", Type: "bigint", NotNull: true,
			Default: "nextval('renamed_seq'::regclass)", SequenceDefault: true, SequenceOwned: true,
		}},
		{"nullable serial", Column{
			Name: "id", Type: "bigint",
			Default: "nextval('events_id_seq'::regclass)", SequenceDefault: true, SequenceOwned: true,
		}},
		{"non-integer type", Column{
			Name: "id", Type: "numeric", NotNull: true,
			Default: "nextval('events_id_seq'::regclass)", SequenceDefault: true, SequenceOwned: true,
		}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			m := base()
			m.Columns[0] = tt.col
			_, err := Render(m)
			require.ErrorIs(t, err, ErrUnrenderableDefault)
		})
	}
}

// Partitioned parents and partitions refuse to render: the model carries no
// partition bounds or topology, so a rendered file would be a silently
// wrong baseline.
func TestRenderRefusesPartitionedTables(t *testing.T) {
	parent := base()
	parent.PartitionKey = "RANGE (id)"
	_, err := Render(parent)
	require.ErrorIs(t, err, ErrUnrenderablePartition)

	child := base()
	child.IsPartition = true
	_, err = Render(child)
	require.ErrorIs(t, err, ErrUnrenderablePartition)
}

func TestRenderRefusesClassicInheritance(t *testing.T) {
	child := base()
	child.InheritsParents = []string{"public.parent"}
	_, err := Render(child)
	require.ErrorIs(t, err, ErrUnrenderableInheritance)

	parent := base()
	parent.InheritanceChildren = []string{"public.child"}
	_, err = Render(parent)
	require.ErrorIs(t, err, ErrUnrenderableInheritance)
}

// A zero-column table is legal PostgreSQL and renders as an empty body,
// not an empty line between the parentheses.
func TestRenderZeroColumnTable(t *testing.T) {
	m := Model{Table: "nocols"}
	out, err := Render(m)
	require.NoError(t, err)
	assert.Equal(t, "CREATE TABLE \"nocols\" ();\n", out)
}

// An unlogged table refuses to render: the model does not manage
// persistence, so a plain CREATE TABLE baseline would silently change the
// table's crash-safety and replication behavior.
func TestRenderRefusesUnloggedTable(t *testing.T) {
	m := base()
	m.Unlogged = true
	_, err := Render(m)
	require.ErrorIs(t, err, ErrUnrenderableUnlogged)
}

// A column with an explicit collation refuses to render: the model does
// not manage collations, so a baseline without the COLLATE clause would
// silently change sort order and index semantics.
func TestRenderRefusesCollatedColumn(t *testing.T) {
	m := base()
	m.Columns[1].Collation = `"C"`
	_, err := Render(m)
	require.ErrorIs(t, err, ErrUnrenderableCollation)
}

// The table's own foreign keys are refused by constraint name under the
// desired-file grammar's sentinel. The cause is driven by the catalog's
// constraint type, not by the definition text, so a flagged constraint
// whose definition does not spell REFERENCES is still named.
func TestRenderRefusesForeignKey(t *testing.T) {
	m := base()
	m.Constraints = append(m.Constraints,
		Constraint{Name: "events_org_fk", Def: "FOREIGN KEY (org_id) REFERENCES orgs(id)", ForeignKey: true},
		Constraint{Name: "events_user_fk", Def: "CHECK (user_id > 0)", ForeignKey: true},
	)

	_, err := Render(m)
	require.ErrorIs(t, err, statement.ErrForeignKey)
	var refusal *RenderRefusal
	require.ErrorAs(t, err, &refusal)
	require.Len(t, refusal.Causes, 1)
	assert.Equal(t, []string{"events_org_fk", "events_user_fk"}, refusal.Causes[0].Objects)
	assert.Equal(t, `render table "events": foreign key constraint(s) events_org_fk, events_user_fk: `+
		statement.ErrForeignKey.Error(), err.Error())
}

// The renderer proves its own output admissible through ParseDesired, so a
// REFERENCES clause the model does not flag still cannot become a
// baseline — it surfaces the parse gate's typed error, not a refusal.
func TestRenderParseGateCatchesUnflaggedForeignKey(t *testing.T) {
	m := base()
	m.Constraints = append(m.Constraints, Constraint{
		Name: "events_user_fk",
		Def:  "FOREIGN KEY (user_id) REFERENCES users(id)",
	})

	_, err := Render(m)
	require.ErrorIs(t, err, statement.ErrForeignKey)
	var refusal *RenderRefusal
	assert.False(t, errors.As(err, &refusal))
}

// A table referenced by other tables' foreign keys refuses to render: the
// single-table model cannot carry incoming foreign-key topology, so a
// rendered baseline would silently drop the table's relationships.
func TestRenderRefusesIncomingForeignKey(t *testing.T) {
	m := base()
	m.ReferencedBy = []string{"orders.orders_user_id_fkey"}

	_, err := Render(m)
	require.ErrorIs(t, err, ErrUnrenderableForeignKey)
	var refusal *RenderRefusal
	require.ErrorAs(t, err, &refusal)
	require.Len(t, refusal.Causes, 1)
	assert.Equal(t, []string{"orders.orders_user_id_fkey"}, refusal.Causes[0].Objects)
	assert.Equal(t, `render table "events": referenced by foreign keys (orders.orders_user_id_fkey): `+
		ErrUnrenderableForeignKey.Error(), err.Error())
}

// A table refused for several reasons names every one of them in one
// refusal — table-level causes first, then each column's in attribute
// order — and the refusal matches every cause's sentinel, so a caller
// explaining why the table cannot be declared needs one call, and a caller
// branching on one sentinel keeps working.
func TestRenderRefusalCollectsEveryCause(t *testing.T) {
	m := base()
	m.Unlogged = true
	m.InheritanceChildren = []string{"public.events_child"}
	m.ReferencedBy = []string{"orders.orders_event_fk"}
	m.Constraints = append(m.Constraints, Constraint{
		Name: "events_user_fk", Def: "FOREIGN KEY (user_id) REFERENCES users(id)", ForeignKey: true,
	})
	m.Columns[1].Collation = `"C"`
	m.Columns = append(m.Columns, Column{
		Name: "seq", Type: "bigint", NotNull: true,
		Default: "nextval('shared_seq'::regclass)", SequenceDefault: true,
	})

	_, err := Render(m)

	var refusal *RenderRefusal
	require.ErrorAs(t, err, &refusal)
	assert.Equal(t, "events", refusal.Table)
	wantErrs := []error{
		ErrUnrenderableInheritance, statement.ErrForeignKey, ErrUnrenderableForeignKey,
		ErrUnrenderableUnlogged, ErrUnrenderableCollation, ErrUnrenderableDefault,
	}
	require.Len(t, refusal.Causes, len(wantErrs))
	for i, want := range wantErrs {
		assert.ErrorIs(t, refusal.Causes[i].Err, want, "cause %d", i)
		assert.ErrorIs(t, err, want)
	}
	assert.Equal(t, []string{"public.events_child"}, refusal.Causes[0].Objects)
	assert.Equal(t, []string{"events_user_fk"}, refusal.Causes[1].Objects)
	assert.Equal(t, []string{"orders.orders_event_fk"}, refusal.Causes[2].Objects)
	assert.Empty(t, refusal.Causes[3].Objects)
	assert.Equal(t, []string{"name"}, refusal.Causes[4].Objects)
	assert.Equal(t, []string{"seq"}, refusal.Causes[5].Objects)
	assert.NotErrorIs(t, err, ErrUnrenderablePartition)
	assert.Equal(t, `render table "events": `+
		`has inheritance children public.events_child: `+ErrUnrenderableInheritance.Error()+`; `+
		`foreign key constraint(s) events_user_fk: `+statement.ErrForeignKey.Error()+`; `+
		`referenced by foreign keys (orders.orders_event_fk): `+ErrUnrenderableForeignKey.Error()+`; `+
		`unlogged table: `+ErrUnrenderableUnlogged.Error()+`; `+
		`column "name" collation "C": `+ErrUnrenderableCollation.Error()+`; `+
		`column "seq" default "nextval('shared_seq'::regclass)": `+ErrUnrenderableDefault.Error(),
		err.Error())
}

// The refusal's Objects are the refusal's own: mutating them afterwards
// does not reach back into the model it was built from.
func TestRenderRefusalClonesObjects(t *testing.T) {
	m := base()
	m.ReferencedBy = []string{"orders.orders_event_fk"}

	_, err := Render(m)
	var refusal *RenderRefusal
	require.ErrorAs(t, err, &refusal)
	refusal.Causes[0].Objects[0] = "changed"
	assert.Equal(t, []string{"orders.orders_event_fk"}, m.ReferencedBy)
}
