package schemadiff

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/block/pg-sprite/pkg/statement"
)

// Rendered SQL is the product artifact a pull produces, so its exact text
// is a legitimate unit-test surface (unlike log output).
func TestRenderGolden(t *testing.T) {
	m := base()
	m.Columns = append(m.Columns,
		Column{Name: "created_at", Type: "timestamp with time zone", NotNull: true, Default: "now()"},
		Column{Name: "doubled", Type: "integer", Generated: true, Default: "(id * 2)"},
		Column{Name: "seq", Type: "bigint", NotNull: true, Identity: IdentityByDefault},
		Column{Name: "note", Type: "text"},
	)
	m.Constraints = append(m.Constraints, Constraint{Name: "name_len", Def: "CHECK ((length((name)::text) > 0))"})

	out, err := Render(m)
	require.NoError(t, err)
	assert.Equal(t, `CREATE TABLE "events" (
    "id" bigint NOT NULL,
    "name" character varying(50) NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "doubled" integer GENERATED ALWAYS AS ((id * 2)) STORED,
    "seq" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "note" text,
    CONSTRAINT "events_pkey" PRIMARY KEY (id),
    CONSTRAINT "name_len" CHECK ((length((name)::text) > 0))
);

CREATE INDEX events_name_idx ON events USING btree (name);
`, out)
}

// A serial column renders back to its pseudo-type so the desired file
// recreates the owned sequence on the scratch schema. All three
// integer-family mappings are exercised so a typo in any one map entry
// fails a test rather than shipping a wrong pseudo-type.
func TestRenderSerialColumn(t *testing.T) {
	tests := []struct {
		colType string
		want    string
	}{
		{"smallint", "smallserial"},
		{"integer", "serial"},
		{"bigint", "bigserial"},
	}
	for _, tt := range tests {
		t.Run(tt.colType, func(t *testing.T) {
			m := base()
			m.Columns[0] = Column{
				Name: "id", Type: tt.colType, NotNull: true,
				Default: "nextval('events_id_seq'::regclass)", SequenceDefault: true,
			}

			out, err := Render(m)
			require.NoError(t, err)
			assert.Contains(t, out, `"id" `+tt.want+` NOT NULL`)
		})
	}
}

// Sequence-backed defaults that are not the canonical serial form fail
// closed: a rendered file could never recreate the sequence they reference.
func TestRenderRefusesUnrenderableSequenceDefaults(t *testing.T) {
	tests := []struct {
		name string
		col  Column
	}{
		{"shared sequence", Column{
			Name: "id", Type: "bigint", NotNull: true,
			Default: "nextval('global_id_seq'::regclass)", SequenceDefault: true,
		}},
		{"nullable serial", Column{
			Name: "id", Type: "bigint",
			Default: "nextval('events_id_seq'::regclass)", SequenceDefault: true,
		}},
		{"non-integer type", Column{
			Name: "id", Type: "numeric", NotNull: true,
			Default: "nextval('events_id_seq'::regclass)", SequenceDefault: true,
		}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			m := base()
			m.Columns[0] = tt.col
			_, err := Render(m)
			require.ErrorIs(t, err, ErrUnrenderableDefault)
		})
	}
}

// Partitioned parents and partitions refuse to render: the model carries no
// partition bounds or topology, so a rendered file would be a silently
// wrong baseline.
func TestRenderRefusesPartitionedTables(t *testing.T) {
	parent := base()
	parent.PartitionKey = "RANGE (id)"
	_, err := Render(parent)
	require.ErrorIs(t, err, ErrUnrenderablePartition)

	child := base()
	child.IsPartition = true
	_, err = Render(child)
	require.ErrorIs(t, err, ErrUnrenderablePartition)
}

// The renderer proves its own output admissible through ParseDesired, so a
// model carrying what a desired file refuses surfaces that gate's typed
// error — a foreign key is the canonical case.
func TestRenderRefusesForeignKey(t *testing.T) {
	m := base()
	m.Constraints = append(m.Constraints, Constraint{
		Name: "events_user_fk",
		Def:  "FOREIGN KEY (user_id) REFERENCES users(id)",
	})

	_, err := Render(m)
	require.ErrorIs(t, err, statement.ErrForeignKey)
}

// A table referenced by other tables' foreign keys refuses to render: the
// single-table model cannot carry incoming foreign-key topology, so a
// rendered baseline would silently drop the table's relationships.
func TestRenderRefusesIncomingForeignKey(t *testing.T) {
	m := base()
	m.ReferencedBy = []string{"orders.orders_user_id_fkey"}

	_, err := Render(m)
	require.ErrorIs(t, err, ErrUnrenderableForeignKey)
}
