// Package schemadiff builds the canonical table model both front-ends share
// and diffs two models into an ordered statement list. The model always
// comes from a real PostgreSQL catalog — the live table is introspected
// directly, and a desired-state file is executed on a transaction-scoped
// scratch schema and introspected the same way, then the transaction is
// rolled back (execute-and-introspect; semantics are never derived from the
// AST). Canonical text (types, defaults, constraint and index definitions)
// is whatever the server's own decompilers print, so cosmetic differences
// (type aliases, default formatting, implicit names) never show up as diffs.
//
// This is a periphery package (see SAFETY.md): its output is a plan request,
// and the core executors re-verify their own preconditions.
package schemadiff

// Identity is a column's identity kind, as pg_attribute.attidentity spells
// it.
type Identity string

// The identity kinds.
const (
	// IdentityNone means the column is not an identity column.
	IdentityNone Identity = ""
	// IdentityAlways is GENERATED ALWAYS AS IDENTITY.
	IdentityAlways Identity = "a"
	// IdentityByDefault is GENERATED BY DEFAULT AS IDENTITY.
	IdentityByDefault Identity = "d"
)

// Column is one column of the canonical model.
type Column struct {
	// Name is the column name.
	Name string
	// Type is the canonical type text (format_type), e.g. "character
	// varying(50)" — never an alias like varchar(50).
	Type string
	// NotNull reports the NOT NULL attribute.
	NotNull bool
	// Default is the canonical default expression (pg_get_expr), empty when
	// none. For a generated column it is the generation expression.
	Default string
	// SequenceDefault reports that the default expression depends on a
	// sequence (per pg_depend) — a serial column or a hand-written nextval
	// default. In a desired-state model that sequence exists only inside
	// the rolled-back scratch transaction, so no derived plan can
	// reference it.
	SequenceDefault bool
	// SequenceOwned reports that the sequence behind the default is owned
	// by this exact column (a pg_depend OWNED BY edge, deptype 'a') — what
	// the serial shorthand produces. It is false for a hand-written
	// nextval default on a standalone sequence or another table's
	// sequence, however the sequence is named: sharing distinguishes it
	// from ownership, not naming.
	SequenceOwned bool
	// Collation is the column's explicit collation as a schema-qualified,
	// quote_ident-quoted name, empty when the column uses its type's
	// default collation. The declarative model does not manage collations yet, so
	// the model carries it only to refuse: dropping a COLLATE clause from
	// a rendered baseline would silently change sort order and index
	// semantics, and a collation delta cannot be converged without a
	// table rewrite.
	Collation string
	// Identity is the identity kind, IdentityNone for plain columns.
	Identity Identity
	// Generated reports GENERATED ALWAYS AS (...) STORED.
	Generated bool
}

// Constraint is one table constraint: its name plus the server-decompiled
// definition (pg_get_constraintdef), e.g. "PRIMARY KEY (id)".
type Constraint struct {
	// Name is the constraint name.
	Name string
	// Def is the canonical definition text.
	Def string
}

// Index is one non-constraint index: its name plus the server-decompiled
// CREATE INDEX statement (pg_get_indexdef), unqualified under the
// introspection search_path.
type Index struct {
	// Name is the index name.
	Name string
	// Def is the canonical CREATE INDEX statement.
	Def string
}

// Model is the canonical, comparison-ready description of one table. It
// carries no schema qualification: the live and desired sides are
// introspected under matching search_path settings so their definitions
// compare textually.
type Model struct {
	// Table is the unqualified table name.
	Table string
	// PartitionKey is the server-decompiled partition key definition
	// (pg_get_partkeydef), e.g. "RANGE (created_at)" — empty for a
	// non-partitioned table.
	PartitionKey string
	// IsPartition reports that the table is itself a partition of a
	// partitioned parent (pg_class.relispartition).
	IsPartition bool
	// InheritsParents lists the classic-inheritance parents of this table.
	// Declarative partitions use the same pg_inherits catalog but are
	// excluded using pg_class.relispartition.
	InheritsParents []string
	// InheritanceChildren lists the classic-inheritance children of this
	// table. The model carries both directions so rendering either side can
	// fail closed rather than flattening inherited columns or losing edges.
	InheritanceChildren []string
	// Unlogged reports that the table is unlogged
	// (pg_class.relpersistence 'u'). The declarative model does not manage
	// persistence yet — converging it (SET LOGGED / SET UNLOGGED) is a
	// full table rewrite — so the model carries it only to refuse:
	// rendering an unlogged table as a plain CREATE TABLE would silently
	// change its crash-safety and replication behavior, and a persistence
	// mismatch fails the diff closed instead of diffing to silence.
	Unlogged bool
	// ReferencedBy lists the incoming foreign keys — constraints on other
	// tables that reference this one — as "table.constraint" strings, in
	// that order. Incoming foreign keys are not part of this table's own
	// definition and cannot be expressed in a desired file, so the model
	// carries them only for the renderer to refuse on.
	ReferencedBy []string
	// Columns are the table's columns in attribute order.
	Columns []Column
	// Constraints are the table constraints, name-sorted.
	Constraints []Constraint
	// Indexes are the non-constraint indexes, name-sorted.
	Indexes []Index
}
