// Package schemadiff builds the canonical table model both front-ends share
// and diffs two models into an ordered statement list. The model always
// comes from a real PostgreSQL catalog — the live table is introspected
// directly, and a desired-state file is executed on a transaction-scoped
// scratch schema and introspected the same way, then the transaction is
// rolled back (execute-and-introspect; semantics are never derived from the
// AST). Canonical text (types, defaults, constraint and index definitions)
// is whatever the server's own decompilers print, so cosmetic differences
// (type aliases, default formatting, implicit names) never show up as diffs.
//
// This is a periphery package (see SAFETY.md): its output is a plan request,
// and the core executors re-verify their own preconditions.
package schemadiff

// Identity is a column's identity kind, as pg_attribute.attidentity spells
// it.
type Identity string

// The identity kinds.
const (
	// IdentityNone means the column is not an identity column.
	IdentityNone Identity = ""
	// IdentityAlways is GENERATED ALWAYS AS IDENTITY.
	IdentityAlways Identity = "a"
	// IdentityByDefault is GENERATED BY DEFAULT AS IDENTITY.
	IdentityByDefault Identity = "d"
)

// Column is one column of the canonical model.
type Column struct {
	// Name is the column name.
	Name string
	// Type is the canonical type text (format_type), e.g. "character
	// varying(50)" — never an alias like varchar(50).
	Type string
	// NotNull reports the NOT NULL attribute.
	NotNull bool
	// Default is the canonical default expression (pg_get_expr), empty when
	// none. For a generated column it is the generation expression.
	Default string
	// SequenceDefault reports that the default expression depends on a
	// sequence (per pg_depend) — a serial column or a hand-written nextval
	// default. In a desired-state model that sequence exists only inside
	// the rolled-back scratch transaction, so no derived plan can
	// reference it.
	SequenceDefault bool
	// Identity is the identity kind, IdentityNone for plain columns.
	Identity Identity
	// Generated reports GENERATED ALWAYS AS (...) STORED.
	Generated bool
}

// Constraint is one table constraint: its name plus the server-decompiled
// definition (pg_get_constraintdef), e.g. "PRIMARY KEY (id)".
type Constraint struct {
	// Name is the constraint name.
	Name string
	// Def is the canonical definition text.
	Def string
}

// Index is one non-constraint index: its name plus the server-decompiled
// CREATE INDEX statement (pg_get_indexdef), unqualified under the
// introspection search_path.
type Index struct {
	// Name is the index name.
	Name string
	// Def is the canonical CREATE INDEX statement.
	Def string
}

// Model is the canonical, comparison-ready description of one table. It
// carries no schema qualification: the live and desired sides are
// introspected under matching search_path settings so their definitions
// compare textually.
type Model struct {
	// Table is the unqualified table name.
	Table string
	// Columns are the table's columns in attribute order.
	Columns []Column
	// Constraints are the table constraints, name-sorted.
	Constraints []Constraint
	// Indexes are the non-constraint indexes, name-sorted.
	Indexes []Index
}
