package plan_test

import (
	"encoding/json"
	"fmt"
	"os"
	"regexp"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/block/pg-sprite/pkg/executor"
	"github.com/block/pg-sprite/pkg/plan"
	"github.com/block/pg-sprite/pkg/planner"
	"github.com/block/pg-sprite/pkg/router"
	"github.com/block/pg-sprite/pkg/schemadiff"
	"github.com/block/pg-sprite/pkg/statement"
	"github.com/block/pg-sprite/pkg/suggest"
)

// planReportDoc is the human-facing contract page these tests keep honest.
const planReportDoc = "../../docs/plan-report.md"

func readDoc(t *testing.T) string {
	t.Helper()
	raw, err := os.ReadFile(planReportDoc)
	require.NoError(t, err)
	return string(raw)
}

// classifyCanonical routes one statement the way both front doors do:
// canonicalize, classify, route.
func classifyCanonical(t *testing.T, sql string) planner.Plan {
	t.Helper()
	canonical, err := statement.Canonical(sql)
	require.NoError(t, err)
	classified, err := planner.Classify(canonical, planner.Facts{})
	require.NoError(t, err)
	return classified
}

// The doc's example reports are generated output, not prose: rebuilding
// them through the real classify-and-route pipeline must reproduce the
// published JSON byte for byte (up to JSON equivalence). If this fails,
// regenerate the examples in docs/plan-report.md.
func TestDocExamplesMatchPipelineOutput(t *testing.T) {
	doc := readDoc(t)
	blocks := regexp.MustCompile("(?s)```json\n(.*?)```").FindAllStringSubmatch(doc, -1)
	require.Len(t, blocks, 3, "the doc publishes one example per source plus a greenfield create-shape refusal")

	alter := plan.NewReport(plan.SourceAlter)
	alter.Schema, alter.Table, alter.ServerVersion = "app", "orders", "16.4"
	alterTableExists := true
	alter.TableExists = &alterTableExists
	routedA := router.Route([]planner.Plan{
		classifyCanonical(t, "ALTER TABLE app.orders DROP COLUMN legacy_status"),
	})
	alter.Disposition = routedA.Disposition
	for _, rs := range routedA.Statements {
		ps, err := plan.FromRouted(rs)
		require.NoError(t, err)
		alter.Statements = append(alter.Statements, ps)
	}
	alter.Fingerprint = plan.Fingerprint(alter.Statements)

	diff := plan.NewReport(plan.SourceDiff)
	diff.Schema, diff.Table, diff.ServerVersion = "app", "orders", "16.4"
	exists := true
	diff.TableExists = &exists
	routedD := router.Route([]planner.Plan{
		classifyCanonical(t, `DROP INDEX "app"."orders_legacy_idx"`),
		classifyCanonical(t, `ALTER TABLE "app"."orders" ADD COLUMN "region" text DEFAULT 'emea'`),
	})
	diff.Disposition = routedD.Disposition
	kinds := []schemadiff.ChangeKind{schemadiff.ChangeDropIndex, schemadiff.ChangeAddColumn}
	for i, rs := range routedD.Statements {
		ps, err := plan.FromRouted(rs)
		require.NoError(t, err)
		ps.Kind = kinds[i]
		diff.Statements = append(diff.Statements, ps)
	}
	diff.Fingerprint = plan.Fingerprint(diff.Statements)

	// Greenfield: no live table, so the desired statements are the plan,
	// qualified onto the target schema, and the create path's shape checks
	// stamp their cause on the statements they refuse.
	greenfield := plan.NewReport(plan.SourceDiff)
	greenfield.Schema, greenfield.Table, greenfield.ServerVersion = "app", "gadgets", "16.4"
	absent := false
	greenfield.TableExists = &absent
	desired, err := statement.ParseDesired(
		"CREATE TABLE IF NOT EXISTS gadgets (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL); " +
			"CREATE INDEX gadgets_name_idx ON gadgets (name)")
	require.NoError(t, err)
	var greenfieldPlans []planner.Plan
	var greenfieldKinds []schemadiff.ChangeKind
	for _, st := range desired.Statements() {
		qualified, err := statement.Qualify(st.SQL(), greenfield.Schema)
		require.NoError(t, err)
		greenfieldPlans = append(greenfieldPlans, classifyCanonical(t, qualified))
		kind := schemadiff.ChangeCreateIndex
		if st.Kind() == statement.KindCreateTable {
			kind = schemadiff.ChangeCreateTable
		}
		greenfieldKinds = append(greenfieldKinds, kind)
	}
	routedG := router.Route(greenfieldPlans)
	greenfield.Disposition = routedG.Disposition
	for i, rs := range routedG.Statements {
		ps, err := plan.FromRouted(rs)
		require.NoError(t, err)
		ps.Kind = greenfieldKinds[i]
		greenfield.Statements = append(greenfield.Statements, ps)
	}
	refused, err := executor.CreateShapeRefusals(greenfield.Schema, desired)
	require.NoError(t, err)
	require.NoError(t, plan.RefuseUnsupportedCreateShape(&greenfield, refused))
	plan.DiscloseGreenfieldExecution(&greenfield)
	greenfield.Fingerprint = plan.Fingerprint(greenfield.Statements)

	for i, want := range []plan.Report{alter, diff, greenfield} {
		raw, err := json.Marshal(want)
		require.NoError(t, err)
		assert.JSONEq(t, blocks[i][1], string(raw),
			"docs/plan-report.md example %d drifted from pipeline output", i+1)
	}
}

// Every vocabulary value the contract closes over must be documented: a
// constant added to the code without a row in docs/plan-report.md (and a
// format_version decision) fails here.
func TestDocListsEveryVocabularyValue(t *testing.T) {
	doc := readDoc(t)
	var values []string
	for _, s := range plan.Sources() {
		values = append(values, string(s))
	}
	for _, r := range planner.Routes() {
		values = append(values, string(r))
	}
	for _, r := range planner.Reasons() {
		values = append(values, string(r))
	}
	for _, e := range planner.Executions() {
		values = append(values, string(e))
	}
	for _, b := range router.Backends() {
		values = append(values, string(b))
	}
	for _, d := range router.Dispositions() {
		values = append(values, string(d))
	}
	for _, k := range schemadiff.ChangeKinds() {
		values = append(values, string(k))
	}
	for _, g := range suggest.Guidances() {
		values = append(values, string(g))
	}
	for _, c := range executor.CreateShapeCauses() {
		values = append(values, string(c))
	}
	for _, v := range values {
		assert.Contains(t, doc, fmt.Sprintf("| `%s` |", v),
			"docs/plan-report.md is missing a vocabulary row for %q", v)
	}
}

// executionModelDoc owns the create-shape cause vocabulary this contract
// embeds; the plan report's Causes table is a copy of its rows.
const executionModelDoc = "../../docs/execution-model.md"

// causeRowMeaning returns the Meaning cell of the vocabulary-table row for
// one create-shape cause, with the sentence-ending period the plan report's
// table style adds stripped so the two docs compare on wording alone.
func causeRowMeaning(t *testing.T, doc, page string, cause executor.CreateShapeCause) string {
	t.Helper()
	prefix := fmt.Sprintf("| `%s` | ", cause)
	for line := range strings.SplitSeq(doc, "\n") {
		if !strings.HasPrefix(line, prefix) {
			continue
		}
		meaning := strings.TrimSuffix(strings.TrimSpace(strings.TrimPrefix(line, prefix)), "|")
		return strings.TrimSuffix(strings.TrimSpace(meaning), ".")
	}
	require.Failf(t, "missing vocabulary row", "%s has no Causes table row for %q", page, cause)
	return ""
}

// The plan report copies the execution model's cause rows rather than
// paraphrasing them: an integrator reading either page must learn the same
// meaning for each value, so the two tables cannot diverge.
func TestDocCauseRowsMatchExecutionModel(t *testing.T) {
	planDoc := readDoc(t)
	raw, err := os.ReadFile(executionModelDoc)
	require.NoError(t, err)
	modelDoc := string(raw)
	for _, cause := range executor.CreateShapeCauses() {
		assert.Equal(t,
			causeRowMeaning(t, modelDoc, "docs/execution-model.md", cause),
			causeRowMeaning(t, planDoc, "docs/plan-report.md", cause),
			"docs/plan-report.md's row for %q drifted from docs/execution-model.md", cause)
	}
}

// The doc's stated current version is the constant, not prose that can
// drift: a FormatVersion bump without the matching doc sentence fails here.
func TestDocStatesCurrentFormatVersion(t *testing.T) {
	doc := readDoc(t)
	assert.Contains(t, doc, fmt.Sprintf("The current version is **%d**", plan.FormatVersion),
		"docs/plan-report.md's stated version drifted from plan.FormatVersion")
}
