package testutil

import (
	"context"
	"errors"
	"fmt"
	"math/rand/v2"
	"sync"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stretchr/testify/require"
)

// WorkloadTable is the fixed-shape table used by copy convergence tests.
type WorkloadTable struct {
	Schema string
	Table  string
	pool   *pgxpool.Pool
	seed   int64
}

// Qualified returns the safely quoted relation name.
func (w WorkloadTable) Qualified() string { return pgx.Identifier{w.Schema, w.Table}.Sanitize() }

// NewWorkloadTable creates an empty workload relation in a unique schema.
func NewWorkloadTable(t *testing.T, pool *pgxpool.Pool) WorkloadTable {
	t.Helper()
	schema := NewSchema(t, pool)
	table := "workload"
	q := `CREATE TABLE ` + pgx.Identifier{schema, table}.Sanitize() + ` (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, uniq integer NOT NULL UNIQUE,
amount numeric(12,2) NOT NULL, label text NOT NULL, blob text,
updated_at timestamptz NOT NULL DEFAULT now())`
	_, err := pool.Exec(t.Context(), q)
	require.NoError(t, err)
	return WorkloadTable{Schema: schema, Table: table, pool: pool, seed: 1}
}

// SeedRows inserts n deterministic rows.
func (w WorkloadTable) SeedRows(ctx context.Context, n int) error {
	q := `INSERT INTO ` + w.Qualified() + ` (uniq, amount, label, blob) SELECT g, g::numeric/100, 'row-'||g, repeat(md5(g::text), 300) FROM generate_series(1,$1) g`
	_, err := w.pool.Exec(ctx, q, n)
	if err != nil {
		return fmt.Errorf("seed workload table %s: %w", w.Qualified(), err)
	}
	return nil
}

// Mix gives relative weights to workload mutations.
type Mix struct {
	Insert     int
	Update     int
	Delete     int
	UniqueMove int
}

// LoadSpec configures a deterministic concurrent workload.
type LoadSpec struct {
	Seed                 int64
	Workers              int
	RatePerSecond        int
	Mix                  Mix
	HotRowFraction       float64
	ToastRewriteFraction float64
}

// Summary reports committed operations and inserted and deleted IDs.
type Summary struct {
	Inserts     int
	Updates     int
	Deletes     int
	UniqueMoves int
	InsertedIDs []int64
	DeletedIDs  []int64
}

// LoadGenerator owns running workload workers.
type LoadGenerator struct {
	cancel  context.CancelFunc
	done    chan struct{}
	mu      sync.Mutex
	summary Summary
	err     error
	stop    sync.Once
}

// StartLoad starts bounded, cancellable workload workers.
func StartLoad(t *testing.T, pool *pgxpool.Pool, table WorkloadTable, spec LoadSpec) *LoadGenerator {
	t.Helper()
	ctx, cancel := context.WithCancel(t.Context())
	g := &LoadGenerator{cancel: cancel, done: make(chan struct{})}
	if spec.Workers < 1 || spec.RatePerSecond < 1 {
		g.err = fmt.Errorf("workers and rate must be positive")
		close(g.done)
		return g
	}
	var wg sync.WaitGroup
	for worker := range spec.Workers {
		wg.Go(func() { g.run(ctx, pool, table, spec, worker) })
	}
	go func() { wg.Wait(); close(g.done) }()
	t.Cleanup(func() { _, _ = g.Stop() })
	return g
}

func (g *LoadGenerator) run(ctx context.Context, pool *pgxpool.Pool, table WorkloadTable, spec LoadSpec, worker int) {
	seed := uint64(spec.Seed) + uint64(worker+1)*0x9e3779b97f4a7c15
	rng := rand.New(rand.NewPCG(seed, seed^0xda3e39cb94b95bdb))
	interval := time.Second / time.Duration(spec.RatePerSecond)
	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			mutationCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), 2*time.Second)
			err := g.mutate(mutationCtx, pool, table, spec, rng)
			cancel()
			if err != nil && !expectedRace(err) {
				g.fail(err)
				g.cancel()
				return
			}
		}
	}
}

func (g *LoadGenerator) mutate(ctx context.Context, pool *pgxpool.Pool, table WorkloadTable, spec LoadSpec, rng *rand.Rand) error {
	total := spec.Mix.Insert + spec.Mix.Update + spec.Mix.Delete + spec.Mix.UniqueMove
	if total <= 0 {
		return fmt.Errorf("mutation mix must have positive weight")
	}
	pick := rng.IntN(total)
	switch {
	case pick < spec.Mix.Insert:
		return g.insert(ctx, pool, table, rng)
	case pick < spec.Mix.Insert+spec.Mix.Update:
		return g.update(ctx, pool, table, spec, rng)
	case pick < spec.Mix.Insert+spec.Mix.Update+spec.Mix.Delete:
		return g.delete(ctx, pool, table, rng)
	default:
		return g.uniqueMove(ctx, pool, table, rng)
	}
}

func (g *LoadGenerator) insert(ctx context.Context, pool *pgxpool.Pool, table WorkloadTable, rng *rand.Rand) error {
	uniq := 1_000_000 + rng.IntN(1_000_000_000)
	var id int64
	err := pool.QueryRow(ctx, `INSERT INTO `+table.Qualified()+` (uniq,amount,label,blob) VALUES ($1,$2,$3,repeat('x',9000)) RETURNING id`, uniq, "1.25", fmt.Sprintf("insert-%d", uniq)).Scan(&id)
	if err == nil {
		g.mu.Lock()
		g.summary.Inserts++
		g.summary.InsertedIDs = append(g.summary.InsertedIDs, id)
		g.mu.Unlock()
	}
	return err
}
func randomIDQuery(table WorkloadTable) string {
	return `SELECT id FROM ` + table.Qualified() + ` ORDER BY random() LIMIT 1`
}
func (g *LoadGenerator) update(ctx context.Context, pool *pgxpool.Pool, table WorkloadTable, spec LoadSpec, rng *rand.Rand) error {
	var id int64
	idQuery := randomIDQuery(table)
	if rng.Float64() < spec.HotRowFraction {
		idQuery = `SELECT id FROM ` + table.Qualified() + ` ORDER BY id LIMIT 1 OFFSET ` + fmt.Sprint(rng.IntN(10))
	}
	if err := pool.QueryRow(ctx, idQuery).Scan(&id); err != nil {
		return err
	}
	rewrite := rng.Float64() < spec.ToastRewriteFraction
	q := `UPDATE ` + table.Qualified() + ` SET amount=amount+1, label=label||'u', updated_at=now()`
	if rewrite {
		q += `, blob=repeat(md5(random()::text),300)`
	}
	q += ` WHERE id=$1`
	tag, err := pool.Exec(ctx, q, id)
	if err == nil && tag.RowsAffected() == 1 {
		g.mu.Lock()
		g.summary.Updates++
		g.mu.Unlock()
	}
	return err
}
func (g *LoadGenerator) delete(ctx context.Context, pool *pgxpool.Pool, table WorkloadTable, rng *rand.Rand) error {
	_ = rng
	var id int64
	err := pool.QueryRow(ctx, `DELETE FROM `+table.Qualified()+` WHERE id=(SELECT id FROM `+table.Qualified()+` ORDER BY random() LIMIT 1) RETURNING id`).Scan(&id)
	if err == nil {
		g.mu.Lock()
		g.summary.Deletes++
		g.summary.DeletedIDs = append(g.summary.DeletedIDs, id)
		g.mu.Unlock()
	}
	return err
}
func (g *LoadGenerator) uniqueMove(ctx context.Context, pool *pgxpool.Pool, table WorkloadTable, rng *rand.Rand) error {
	_ = rng
	tx, err := pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback(context.WithoutCancel(ctx)) }()
	rows, err := tx.Query(ctx, `SELECT id,uniq FROM `+table.Qualified()+` ORDER BY random() LIMIT 2 FOR UPDATE`)
	if err != nil {
		return err
	}
	type pair struct {
		ID   int64
		Uniq int
	}
	values, err := pgx.CollectRows(rows, pgx.RowToStructByPos[pair])
	if err != nil {
		return err
	}
	if len(values) < 2 {
		return nil
	}
	temp := -2_000_000_000 + rng.IntN(100_000_000)
	for _, args := range [][]any{{temp, values[0].ID}, {values[0].Uniq, values[1].ID}, {values[1].Uniq, values[0].ID}} {
		if _, err = tx.Exec(ctx, `UPDATE `+table.Qualified()+` SET uniq=$1,updated_at=now() WHERE id=$2`, args...); err != nil {
			return err
		}
	}
	if err = tx.Commit(ctx); err == nil {
		g.mu.Lock()
		g.summary.UniqueMoves++
		g.mu.Unlock()
	}
	return err
}
func expectedRace(err error) bool {
	if errors.Is(err, pgx.ErrNoRows) || errors.Is(err, context.Canceled) {
		return true
	}
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && (pgErr.Code == "23505" || pgErr.Code == "40001" || pgErr.Code == "40P01")
}
func (g *LoadGenerator) fail(err error) {
	g.mu.Lock()
	defer g.mu.Unlock()
	if g.err == nil {
		g.err = err
	}
}

// Stop promptly cancels workers and waits at most five seconds for completion.
func (g *LoadGenerator) Stop() (Summary, error) {
	g.stop.Do(g.cancel)
	deadline := time.NewTimer(5 * time.Second)
	defer deadline.Stop()
	select {
	case <-g.done:
	case <-deadline.C:
		return Summary{}, fmt.Errorf("stop load generator: deadline exceeded")
	}
	g.mu.Lock()
	defer g.mu.Unlock()
	return g.summary, g.err
}
