CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text,
    name varchar(50),
    status text DEFAULT 'active'
);
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
CREATE POLICY active_users ON users FOR SELECT USING (status = 'active');
