CREATE TABLE users (
    id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email  text,
    name   varchar(50),
    status text DEFAULT 'active',
    bio    text
);

CREATE INDEX idx_users_bio ON users (bio);
