-- Baseline schema and data for the demo tour. Rerunnable: drops and
-- recreates everything, so every `make demo` starts from the same state.
-- Identity (not serial) keys so the declarative diff never meets a
-- sequence-backed default it must refuse.
DROP TABLE IF EXISTS users, orders, widgets CASCADE;

CREATE TABLE users (
    id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email  text,
    name   varchar(50),
    status text DEFAULT 'active'
);

-- Enough rows that constraint validation and index builds do visible work,
-- small enough to stay instant. Every email is non-null so the SET NOT NULL
-- tour step's VALIDATE passes.
INSERT INTO users (email, name)
SELECT 'u' || g || '@example.com', 'user ' || g
FROM generate_series(1, 10000) g;

CREATE TABLE orders (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer,
    total   numeric(10,2)
);

INSERT INTO orders (user_id, total)
SELECT (g % 10000) + 1, g
FROM generate_series(1, 5000) g;
